language: ruby
rvm:
  - 2.2.0
  - 2.1.5
  - 2.0.0
  - 1.9.3
before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -O- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y rethinkdb
  - sudo pip install rethinkdb
  - sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/instance1.conf
  - sudo /etc/init.d/rethinkdb restart
  - bundle install
